version: "3"

services:
  my-docker-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
